### ISSUE TITLE
cant resolve path nor types on import

### ISSUE THREAD

**Issue by iwpnd** [batrdn/nock-graphql#2]
Hi :wave:

I was really looking forward for a nock like approach to graphql mocking. I followed your readme, but failed miserably to even import `NockGraphQL` in my monorepo x lerna setup sporting typescript 4.3.5.

```
'NockGraphQL' is declared but its value is never read. ts (6133)
Unable to resolve path to module 'nock-graphql'. eslint (import/no-unresolved)
Cannot find module 'nock-graphql' or its corresponding type declarations. ts(2307)
```

The whole [Apollo migration to v3](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/) already causes a lot of trouble. And for whatever reason ([solution still pending](https://github.com/apollographql/apollo-client/issues/6376#issuecomment-834050272)) you have to include `"lib": ["dom"]` in your `tsconfig.ts` to fix a lot of the typing issues describe in that [thread](https://github.com/apollographql/apollo-client/issues/6376#issuecomment-834050272).

I don't know if that's much to go on, but maybe you have an idea?

**Comment by batrdn** [comment]
Hi,
Thanks for letting me know of this issue. It is now fixed in the latest release (v1.1.6)
